### ISSUE TITLE
我做了一个 本wiki的LOGO

### ISSUE THREAD

**Issue by monicfenga** [Evisolpxe/OsuCNwiki#14]
我注意到这个wiki的logo是绿色的，我认为不是很适合。
于是我简单做了一个：
粉红色的圆形（代表这个游戏），里面有一本书（代表知识）

![osucnwiki-logo.png](https://fbi.gs/2019/11/19/8dd8a3dd7460a.png)

**Comment by Pure-Peace** [comment]
看起来不错

**Comment by Evisolpxe** [comment]
抱歉太久未回，链接失效了可否再发一遍？

**Comment by monicfenga** [comment]
> 抱歉太久未回，链接失效了可否再发一遍？

![osucnwiki-logo](https://user-images.githubusercontent.com/39868412/76737377-9e37ab00-67a3-11ea-8381-b73b25bae5eb.png)

@Evisolpxe

**Comment by Evisolpxe** [comment]
> > 抱歉太久未回，链接失效了可否再发一遍？
> 
> ![osucnwiki-logo](https://user-images.githubusercontent.com/39868412/76737377-9e37ab00-67a3-11ea-8381-b73b25bae5eb.png)
> 
> @Evisolpxe

已经添加至gitbook主页！十分感谢
