### ISSUE TITLE
Review of osu! Tools 可以增加一些 bot 相关的内容

### ISSUE THREAD

**Issue by Miracle3310** [Evisolpxe/OsuCNwiki#26]
可以更新一下osu相关的聊天机器人库。
记一下希望之后我别忘了。（（

还有一些油猴插件之类的。

**Comment by Evisolpxe** [comment]
目前开源是不是只有白菜来着

**Comment by Miracle3310** [comment]
qq我暂时也只知道白菜，，

不过不局限于qq吧，discord上也有挺多有意思的bot比如可以渲染rep [flowabot](https://github.com/LeaPhant/flowabot)，还有比如osu内的mp自动轮房主的bot。
