### ISSUE TITLE
wacom官方驱动

### ISSUE THREAD

**Issue by 1553767977** [Evisolpxe/OsuCNwiki#29]
![image](https://user-images.githubusercontent.com/39228172/194738805-97f42067-9f51-4df0-9699-cef79c5b221c.png)
重新启动限制是因为wacom服务没有运行，在本地服务中找到Wacom Professional Service，启动此服务即可让数位板驱动运行

**Comment by Evisolpxe** [comment]
好的！我会把处理方法加在文中。
不过现在用官方驱动的人应该很少了
