### ISSUE TITLE
Add traditional chinese support

### ISSUE THREAD

**Issue by Deardrops** [Evisolpxe/OsuCNwiki#9]
因为 gitbook 官方目前[没有支持多语言](https://docs.gitbook.com/v2-changes/important-differences#multi-language-books)，建议新开一个 repo 放繁体中文版本，用工具同步所有内容。  
建议使用 [OpenCC](https://github.com/BYVoid/OpenCC) 进行简繁转换。

**Comment by Evisolpxe** [comment]
收到，会将繁体版提上日程！
不过目前项目还处于快速迭代状态，很多项目正在增改并确定稳定版本，在项目基本完成后才会制作其他版本。
